import { Navbar } from "@/components/landing/navbar";
import { Footer } from "@/components/landing/footer";

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-28 pb-20 px-6">
        <div className="max-w-3xl mx-auto prose prose-gray">
          <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
          <p className="text-brand-muted mb-8">Last updated: August 28, 2026</p>

          <section className="space-y-4 text-sm leading-relaxed text-brand-text/80">
            <h2 className="text-lg font-semibold text-brand-text">1. Acceptance of Terms</h2>
            <p>By accessing or using Revox AI, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.</p>

            <h2 className="text-lg font-semibold text-brand-text">2. Description of Service</h2>
            <p>Revox AI provides AI-powered video translation services, including speech transcription, text translation, and voice cloning. The service allows users to translate video content into multiple languages while preserving the original speaker&apos;s voice characteristics.</p>

            <h2 className="text-lg font-semibold text-brand-text">3. Account Registration</h2>
            <p>You must create an account to use Revox AI. You are responsible for maintaining the security of your account and for all activities that occur under your account. You must provide accurate information when creating your account.</p>

            <h2 className="text-lg font-semibold text-brand-text">4. Acceptable Use</h2>
            <p>You agree NOT to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Upload content you do not have the rights to translate</li>
              <li>Use the service for illegal, harmful, or fraudulent purposes</li>
              <li>Upload content that is illegal, abusive, or violates others&apos; rights</li>
              <li>Attempt to bypass usage limits or security measures</li>
              <li>Resell access to the service without authorization</li>
              <li>Use the service to create deepfakes or misleading content</li>
              <li>Impersonate others using voice cloning</li>
            </ul>

            <h2 className="text-lg font-semibold text-brand-text">5. Content Rights</h2>
            <p>You retain ownership of all content you upload. By using the service, you grant us a temporary license to process your content for translation purposes only. We do not claim ownership of your content and will not use it for any other purpose.</p>
            <p>You are solely responsible for ensuring you have the right to translate the content you upload. This includes having the necessary licenses, permissions, or fair use rights.</p>

            <h2 className="text-lg font-semibold text-brand-text">6. Subscription and Payments</h2>
            <p>Revox AI offers free and paid subscription tiers. Paid subscriptions are billed monthly through Stripe. You can cancel your subscription at any time — your access continues until the end of the current billing period.</p>
            <p>Prices may change with 30 days notice. Refunds are handled on a case-by-case basis.</p>

            <h2 className="text-lg font-semibold text-brand-text">7. Usage Limits</h2>
            <p>Each subscription tier has specific usage limits including monthly minutes, maximum video length, and available languages. These limits reset at the beginning of each billing cycle. Exceeding your limits will require upgrading your plan.</p>

            <h2 className="text-lg font-semibold text-brand-text">8. Service Availability</h2>
            <p>We strive to maintain high availability but do not guarantee uninterrupted service. We may perform maintenance, updates, or experience downtime. We are not liable for any losses resulting from service interruptions.</p>

            <h2 className="text-lg font-semibold text-brand-text">9. AI-Generated Content</h2>
            <p>Translations and voice cloning are generated by AI and may not be perfect. We do not guarantee 100% accuracy of translations or voice reproduction. You are responsible for reviewing the output before distributing it.</p>

            <h2 className="text-lg font-semibold text-brand-text">10. Limitation of Liability</h2>
            <p>Revox AI is provided &quot;as is&quot; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability is limited to the amount you paid for the service in the 12 months preceding the claim.</p>

            <h2 className="text-lg font-semibold text-brand-text">11. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time. Upon termination, your data will be deleted according to our Privacy Policy.</p>

            <h2 className="text-lg font-semibold text-brand-text">12. Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms.</p>

            <h2 className="text-lg font-semibold text-brand-text">13. Contact</h2>
            <p>For questions about these terms, contact us at <a href="mailto:sam.fan2009@gmail.com" className="text-brand-primary hover:underline">sam.fan2009@gmail.com</a>.</p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
