import { Navbar } from "@/components/landing/navbar";
import { Footer } from "@/components/landing/footer";

export default function DisclaimerPage() {
  return (
    <>
      <Navbar />
      <main className="pt-28 pb-20 px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold tracking-tight mb-2">Disclaimer</h1>
          <p className="text-brand-muted mb-8">Last updated: August 28, 2026</p>

          <section className="space-y-4 text-sm leading-relaxed text-brand-text/80">
            <h2 className="text-lg font-semibold text-brand-text">General Disclaimer</h2>
            <p>Revox AI is provided on an &quot;as is&quot; and &quot;as available&quot; basis without warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, or completely secure.</p>

            <h2 className="text-lg font-semibold text-brand-text">AI Translation Accuracy</h2>
            <p>All translations are generated by artificial intelligence and may contain errors, inaccuracies, or mistranslations. Revox AI does NOT guarantee:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>100% accuracy of any translation</li>
              <li>Perfect reproduction of the original speaker&apos;s voice</li>
              <li>Suitability of translations for legal, medical, or safety-critical purposes</li>
              <li>Cultural appropriateness of translations in all contexts</li>
            </ul>
            <p><strong>You are solely responsible for reviewing and verifying all translations before distributing or publishing them.</strong></p>

            <h2 className="text-lg font-semibold text-brand-text">Not a Substitute for Professional Translation</h2>
            <p>Revox AI is not a substitute for professional human translation services. For content requiring certified accuracy (legal documents, medical information, safety instructions, official government communications), we strongly recommend using a certified human translator.</p>

            <h2 className="text-lg font-semibold text-brand-text">Voice Cloning Disclaimer</h2>
            <p>Our voice cloning technology creates an approximation of the original speaker&apos;s voice. The output may differ from the original voice in tone, accent, pronunciation, or emotional expression. We do not guarantee that the cloned voice will be indistinguishable from the original.</p>

            <h2 className="text-lg font-semibold text-brand-text">Third-Party Content</h2>
            <p>Revox AI is not responsible for any content uploaded by users. We do not endorse, verify, or take responsibility for user-generated content or the translations produced from it.</p>

            <h2 className="text-lg font-semibold text-brand-text">Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Revox AI and its owners, operators, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Your use or inability to use the service</li>
              <li>Any errors or inaccuracies in translations</li>
              <li>Unauthorized access to your data</li>
              <li>Loss of data, revenue, or profits</li>
              <li>Any third-party conduct on the service</li>
              <li>Any content uploaded, translated, or distributed using the service</li>
            </ul>

            <h2 className="text-lg font-semibold text-brand-text">Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless Revox AI and its owners from any claims, damages, losses, or expenses (including legal fees) arising from your use of the service, your violation of these terms, or your violation of any third-party rights.</p>

            <h2 className="text-lg font-semibold text-brand-text">External Links</h2>
            <p>Our service may contain links to third-party websites. We are not responsible for the content, privacy practices, or policies of any third-party sites.</p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
